#sudo: require
#services:
# - docker

# before_install:
#  - docker build -t naufalnadeem/docker-react -f Dockerfile.dev . #image tagged to naufalnadeem/reponame

 language: node_js

 node_js:
   - "14.17.3"

install:
  - npm install

script:
  - docker build -t naufalnadeem/docker-react -f Dockerfile.dev . 
