sudo: require
services:
 - docker

before_install:
 - docker build -t naufalnadeem/docker-react -f Dockerfile.dev . #image tagged to naufalnadeem/reponame

script:
 - docker run -e CI=true naufalnadeem/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk 
 region: 'us-east-2'
 app: 'Docker'
 env: 'Docker-env'
 bucket_name: 'elasticbeanstalk-us-east-2-784795358450'
 bucket_path: 'Docker'
 on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secreat_access_key: $AWS_SECREAT_KEY
   