sudo: require
services:
 - docker

before_install:
 - docker build -t naufalnadeem/docker-react -f Dockerfile.dev . #image tagged to naufalnadeem/reponame

script:
 - docker run -e CI=true naufalnadeem/docker-react npm run test -- --coverage

