version: '3'
services:
 web:
  build:
   context: . #where we want all files and folders to come from
   dockerfile: Dockerfile.dev
  ports:
   - "3000:3000"
  volumes:
   - /app/node_modules
   - .:/app